# Generated by Django 5.1.7 on 2025-03-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='passive',
            field=models.BooleanField(default=False),
        ),
    ]
