# Generated by Django 5.1.7 on 2025-03-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_treatment_passive'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
