# Generated by Django 5.1.7 on 2025-03-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_suggestion_effectiveness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='passive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
